"""init_auth_infra

Revision ID: 0001
Revises:
Create Date: 2025-08-21 10:30:00.000000

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("auth",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS citext")
    op.execute("DROP SCHEMA IF EXISTS auth CASCADE")
    # ### end Alembic commands ###
